files:
  - source: /common/src/main/resources/lang/en.json
    translation: /common/src/main/resources/lang/%locale_with_underscore%.json
    languages_mapping:
      locale_with_underscore:
        bg: bg
        de: de
        es-ES: es
        fr: fr
        pl: pl
        pt-PT: pt
        ru: ru
        tr: tr
        zh-CN: zh_CN
