name: Chunky
version: ${projectVersion}
main: org.popcraft.chunky.ChunkyBukkit
api-version: "1.13"
softdepend: [dynmap, BlueMap, Pl3xMap, WorldBorder]
load: POSTWORLD
authors: [pop4959]
description: Pre-generates chunks, quickly, efficiently, and safely
website: https://www.spigotmc.org/resources/chunky.81534/
commands:
  chunky:
    description: Generates chunks
    aliases: [cy]
    permission: chunky.chunky
    usage: /chunky
permissions:
  chunky.chunky:
    description: Generates chunks
    default: op
